name: ManualChoice
on: 
 workflow_dispatch:
  inputs:
    log-level:
    type: choice
    options:
      - info
      - warn
      - error

jobs:
  choice_label:
  runs-on: ubuntu-latest
  steps:
    - run: echo"${{inputs.log-level}}""
  

